In [47]:
import numpy as np
from Classes import *
import scipy as sc
a=np.ones((2,2),float)
b=sc.sparse.block_diag((a,a))
print(b.toarray())
ll=[b,b,b]
sum(ll).toarray()

[[ 1.  1.  0.  0.]
 [ 1.  1.  0.  0.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  1.  1.]]


array([[ 3.,  3.,  0.,  0.],
       [ 3.,  3.,  0.,  0.],
       [ 0.,  0.,  3.,  3.],
       [ 0.,  0.,  3.,  3.]])

In [41]:
a=1.
type(a)
b=(a,a)
type(b)

tuple

In [42]:
from Classes import * 
from Simu import *
from NLL import *
import numpy as np
import matplotlib.pyplot as plt
import scipy as sc
from scipy import integrate
import sympy as sy
from scipy import linalg
import pylab as pl
import math as ma
import time 


sig=3.
el=0.3
per=0.1

def kfonc(s,t):
    return Periodic(el,per,sig).val([s,t]);

print time.clock()
print "scipy dblquad contrôlé"
def gfun(x): return 0;
def hfun(x): return 1;
print integrate.dblquad(kfonc, 0, 1, gfun, hfun, epsabs=5e-03)
print time.clock()
print "scipy nquad contrôlé"
print integrate.nquad(kfonc,[[0,1],[0,1]],opts=[{'epsabs':5e-03},{'epsabs':5e-03}])
print time.clock()

print "ma méthode récu"
print Integ( Periodic(el,per,sig),np.array([0,0]),np.array([1,1]),100 ).val()
print time.clock()
print "ma méthode array"
print Integ_cub(Periodic(el,per,sig),np.array([0,0]),np.array([1,1]),100 ).val()[0]
print time.clock()
print "ma méthode MC"
print Integ_MC( Periodic(el,per,sig),np.array([0,0]),np.array([1,1]),n=1000 ).val()
print time.clock()

print "vraie val"
print integrate.dblquad(kfonc, 0, 1, gfun, hfun)
print time.clock()




6345.42413463
scipy dblquad contrôlé
(4.075688215592129, 0.0003779785190177747)
6345.9101143
scipy nquad contrôlé
(4.075688180580958, 0.004713710450750562)
6346.08007916
ma méthode récu


Classes.py:269: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  Prod=Prod*(self.borne_sup[i]-self.borne_inf[i])
Classes.py:276: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  x[:,dim]= vec[dim]+np.arange(J+1)*1.*(self.borne_sup[dim]-vec[dim])/J


4.07236777288
6346.41995963
ma méthode array


Classes.py:322: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  mini_Tab[:,i]= self.borne_inf[dim] + np.arange(J+1)*1.*(self.borne_sup[dim]-self.borne_inf[dim])/J
Classes.py:345: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  Prod=Prod*(self.borne_sup[i]-self.borne_inf[i])
Classes.py:370: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  Vol=Vol*(self.borne_sup[i]-self.borne_inf[i])


4.07236777288
6346.70969697
ma méthode MC
[ 4.16823668]
6346.74987592
vraie val
(4.072661198896048, 2.382339793801167e-08)
6355.98919262


# Accélération de l'intégration par l'utilisation de fonction vectorielle numpy plutôt que de classes python
Commençons par noter qu'il est possible de donner à la fonction np.apply_along_axis une fonction qui prend plusieurs arguments. Il suffit pour cela de fournir les arrays de chaque argument à la file.   

In [ ]:
def car(a,b):
    return a+b;

li=[1,2,3]
li2=li
print(np.apply_along_axis(car,0,li,li2 ))


Si le nombre d'arguments n'est pas connu à l'avance on peut avoir recours à une asture : la commande * permet de transformer une liste (iterable) de variables en une suite de variables similaire au format de l'exemple ci-dessus, mais avec un nombre indéterminé de variables.   

In [ ]:
a=[[0,1,2,3],[0,1,2,3]]
print("res")
print(np.apply_along_axis(car,0,*a ))


On peut alor simplement définir une expression Sympy, la convertir en fonction vectorielle numpy et approximer l'intégrale avec la classe Integ_fo qui intègre ce changement par rapport à la version Integ. 

In [1]:
t=sy.Symbol('t')
s=sy.Symbol('s')
lin=t+s
fonction=sy.lambdify((t,s),lin,"numpy")
print(Integ_fo(fonction,np.array([0,0]),np.array([1,1]),50).val())

NameError: name 'sy' is not defined

Cela rend le calcul beaucoup plus rapide car la fonction que nous avons définie est correctement vectorisée par numpy.

In [ ]:
t=sy.Symbol('t')
s=sy.Symbol('s')
lin=sy.exp(-(t-s)**2/2)
f_lin=sy.lambdify((t,s),lin,"numpy")
print(time.clock())
print(Integ_fo(f_lin,np.array([0,0]),np.array([1,1]),500).val())
print(time.clock())
ktest=RBF(1.,1.)
print(Integ(ktest,np.array([0,0]),np.array([1,1]),500).val())
print(time.clock())